#!/usr/bin/env sh
set -e

echo "[LOG] CREATE DATABASE IF NOT EXISTS $PGDATABASE"
env PGPASSWORD="$PGPASSWORD" PGHOST="$PGHOST" PGPORT="$PGPORT" psql -v ON_ERROR_STOP=1 --username "$PGUSER" --dbname "postgres"  <<-EOSQL
SELECT 'CREATE DATABASE $PGDATABASE' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$PGDATABASE')\gexec
EOSQL

echo "[LOG] CREATE USER $DB_USERNAME IF NOT EXISTS"
env PGPASSWORD="$PGPASSWORD" PGHOST="$PGHOST" PGPORT="$PGPORT" psql -v ON_ERROR_STOP=1 --username "$PGUSER" --dbname "postgres"  <<-EOSQL
DO
\$do$
BEGIN
   IF EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = '$DB_USERNAME') THEN

      RAISE NOTICE 'Role "$DB_USERNAME" already exists. Skipping.';
   ELSE
      CREATE ROLE $DB_USERNAME LOGIN ENCRYPTED PASSWORD '$DB_PASSWORD';
   END IF;
END
\$do$;
GRANT ALL ON DATABASE $PGDATABASE TO $DB_USERNAME;
EOSQL
